// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeBHdH-bYlxxYsPD0GDR8wlHH1VEKAXFE',
    appId: '1:634220758335:web:5d67dc97bcfd2906083f8a',
    messagingSenderId: '634220758335',
    projectId: 'growthron-3f221',
    authDomain: 'growthron-3f221.firebaseapp.com',
    databaseURL: 'https://growthron-3f221-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'growthron-3f221.appspot.com',
    measurementId: 'G-FT7CXW9QY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh-PPQWmyMxbHcTVlpRUTkIXp54sNt4pU',
    appId: '1:634220758335:android:8066dfc94c113311083f8a',
    messagingSenderId: '634220758335',
    projectId: 'growthron-3f221',
    databaseURL: 'https://growthron-3f221-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'growthron-3f221.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAus2rRMmu9FTirL8yap4y3p4pFgIbvApI',
    appId: '1:634220758335:ios:71ab7e34c87bb2f0083f8a',
    messagingSenderId: '634220758335',
    projectId: 'growthron-3f221',
    databaseURL: 'https://growthron-3f221-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'growthron-3f221.appspot.com',
    androidClientId: '634220758335-8lmpdrnopph207gg43j0p86ga9k441sn.apps.googleusercontent.com',
    iosClientId: '634220758335-j087k28illl11gei2mdqsbocp76sklck.apps.googleusercontent.com',
    iosBundleId: 'com.example.growthclub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAus2rRMmu9FTirL8yap4y3p4pFgIbvApI',
    appId: '1:634220758335:ios:71ab7e34c87bb2f0083f8a',
    messagingSenderId: '634220758335',
    projectId: 'growthron-3f221',
    databaseURL: 'https://growthron-3f221-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'growthron-3f221.appspot.com',
    androidClientId: '634220758335-8lmpdrnopph207gg43j0p86ga9k441sn.apps.googleusercontent.com',
    iosClientId: '634220758335-j087k28illl11gei2mdqsbocp76sklck.apps.googleusercontent.com',
    iosBundleId: 'com.example.growthclub',
  );
}
